'''Q15. Give the scenarios, when you will get ValueError'''


'''ValueError is a built-in Python exception that is raised when the type of a passed argument 
to a function is incorrect or when a function is called with an argument that has an invalid value'''

a=int(input())
b=str(input())
print(a)
print(b)

c=str(a)
print(c,end=' -> ')
print(type(c))
# print(float(a))



